[package]
name = "projet"
version = "0.1.0"

[dependencies]
derive_more = "0.99.0"
rand = "0.8.5"
bumpalo = "3.11.1"
clap = { version = "4.0.32", features = ["derive"] }
crossbeam = "0.8.2"
chrono = {version =  "0.4.23", features = ["clock"] }
ctrlc = "3.2.4"
rustyline = "10.0.0"